CREATE TABLE BABY_COMMISSION
(
    ID            VARCHAR2(30)    NOT NULL, 
    COMMISSION    VARCHAR2(30)       NULL   
);

ALTER TABLE BABY_COMMISSION
    ADD CONSTRAINT FK_BABY_COMMISSION_ID_BABY_MEM FOREIGN KEY (ID)
        REFERENCES BABY_MEMBER (ID);