drop table SITTER_BOARD_COMMENT CASCADE CONSTRAINTS;


CREATE TABLE SITTER_BOARD_COMMENT
(
    SEQ              NUMBER(30)       NOT NULL, 
    BOARD_COMMENT    VARCHAR2(2000)    NULL, 
    REGISTER_DATE    DATE            NULL   
)

ALTER TABLE SITTER_BOARD_COMMENT
    ADD CONSTRAINT FK_SITTER_BOARD_COMMENT_SEQ_SI FOREIGN KEY (SEQ)
        REFERENCES SITTER_BOARD (SEQ);
/